import { ParamsDictionary, Request } from 'express-serve-static-core';
import { ParsedQs } from 'qs';
import { HttpRequest } from '@azure/functions';

/**
 * Represents the required options to us the auth middleware
 */
export interface AuthMiddlewareOptions {
  domain: string;
  audience: string;
}

/**
 * Represents a user token generated by express-jwt
 *
 * sub is the users id in auth0
 */
export interface UserToken {
  iss: string;
  sub: string;
  aud: string[];
  iat: number;
  exp: number;
  azp: string;
  scope: string;
}

/**
 * Represents an acceptable request for JWT
 */
export type MiddleWareRequest = Request<
  ParamsDictionary,
  any,
  any,
  ParsedQs,
  Record<string, any>
>;

/**
 * Represents a request handled by the auth middleware.
 *
 * userId is the same as user.sub, it is just for convenience
 * that it is set as userId.
 */
export interface AuthReqest extends HttpRequest {
  userId?: string;
  user?: UserToken;
}
